---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  description: dev project
  sourceRepos:
  - '*'
  destinations:
  - namespace: "dev"
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
