---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  description: prod project
  sourceRepos:
  - '*'
  destinations:
  - namespace: "prod"
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
