helmDefaults:
  atomic: false
  wait: false
  cleanupOnFail: false
  timeout: 300

# don't move this into separate file, or you're going to lose dynamic helm chart releases per environment
environments:
  dev:
    values:
      - config/environments/common.yaml
      - config/environments/dev.yaml
  prod:
    values:
      - config/environments/common.yaml
      - config/environments/prod.yaml
---
repositories:
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: codecentric
    url: https://codecentric.github.io/helm-charts
releases:
  # helm chart for metrics-server is here https://artifacthub.io/packages/helm/metrics-server/metrics-server
  - name: metrics-server
    namespace: kube-system
    createNamespace: true
    missingFileHandler: Warn
    labels:
      app: metrics-server
    chart: metrics-server/metrics-server
    version: 3.11.0
    values:
      - ./config/values/metrics-server.values.yaml
      - ./config/values/{{ .Environment.Name }}/metrics-server.values.yaml
  - name: mailhog
    namespace: mailhog
    missingFileHandler: Warn
    createNamespace: true
    labels:
      app: mailhog
      backstage.io/kubernetes-id: mailhog
    chart: codecentric/mailhog
    version: 5.2.3
    values:
      - ./config/values/mailhog.values.yaml
      - ./config/values/{{ .Environment.Name }}/mailhog.values.yaml
