version: 3

tasks:
  build:
    desc: build container image
    cmds:
      - docker build -t ghcr.io/labotomy-dot-dev/coffee-cup:latest ./src
      
  push:
    desc: push container image
    cmds:
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u labotomy-dot-dev --password-stdin
      - docker push ghcr.io/labotomy-dot-dev/coffee-cup:latest
  deploy.dev:
    desc: deploy to dev
    cmds:
      - kubectl apply -f deploy/dev/namespace.yaml && kubectl apply -f deploy/dev/deploy.yaml
  deploy.prod:
    desc: deploy to prod
    cmds:
      - kubectl apply -f deploy/prod/namespace.yaml && kubectl apply -f deploy/prod/deploy.yaml