apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-cup-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/labotomy-dot-dev/coffee-cup.git'
    targetRevision: dev
    path: deploy/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
