apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-cup-prod
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: 'https://github.com/labotomy-dot-dev/coffee-cup.git'
    targetRevision: main
    path: deploy/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
