apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailhog
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: platform
  source:
    repoURL: https://github.com/labotomy-dot-dev/coffee-cup.git
    targetRevision: HEAD
    path: gitops/platform/manifests/generated/dev/mailhog/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: mailhog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true