apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-dev
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: platform
  source:
    repoURL: https://github.com/labotomy-dot-dev/coffee-cup.git
    targetRevision: HEAD
    path: gitops/platform/manifests/manual/metrics-server
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true