name: Catch ArgoCD Events

on:
  repository_dispatch:

jobs:
  print-payload:
    runs-on: ubuntu-latest
    steps:
      - name: Print raw GitHub event
        run: |
          echo "===================="
          echo "GitHub event JSON:"
          cat $GITHUB_EVENT_PATH
          echo "===================="

      - name: Print formatted JSON
        run: |
          echo "Formatted event:"
          cat $GITHUB_EVENT_PATH | jq
