name: Print payload for troubleshooting

# 👇 Dynamic workflow run name appears in the Actions UI
run-name: |
  [${{ github.event.client_payload.project || 'unknown' }}] \
  ${{ github.event.client_payload.app || 'no-app' }} \
  (rev: ${{ github.event.client_payload.app_revision || 'n/a' }}) \
  -> ${{ github.event.action || github.event_name }}

on:
  repository_dispatch:
    types:
      - argocd-on-prod-deployed
      - argocd-on-dev-deployed
      - argocd-on-prod-failed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  payload-print:
    name: Print ArgoCD webhook payload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print payload
        run: |
          echo "Payload:"
          echo "${{ toJson(github.event.client_payload) }}"
